version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    parallelism: 2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            mkdir ~/project/test-report
            pytest --junit-xml=test-report/report.xml $(circleci tests glob "openapi_server/**/test_*.py" | circleci tests split --split-by=timings)
      - store_test_results:
          path: ~/project/test-report/report.xml
      - store_artifacts:
          path: ~/project/test-report

workflows:
  sample:
    jobs:
      - build-and-test